project:
  type: website

website:
  title: RapidSurveys
  site-url: https://rapidsurveys.io
  navbar:
    title: RapidSurveys
    logo: images/rapidsurveys_neg.png
    logo-alt: RapidSurveys
    tools:
      - icon: mastodon
        aria-label: Mastodon
        href: https://fosstodon.org/@katilingban
        rel: me
      - icon: linkedin
        aria-label: LinkedIn
        href: https://linkedin.com/company/katilingban
      - icon: github
        aria-label: GitHub
        href: https://github.com/rapidsurveys
    left:
      - href: index.qmd
        text: Home
      - text: Packages
        href: packages/index.qmd
      - text: About
        menu:
          - href: about/team.qmd
          - href: about/contact.qmd
  open-graph:
    site-name: RapidSurveys
  page-footer:
    center: "Copyright 2024-2026, Katilingban"
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/rapidsurveys/rapidsurveys.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/rapidsurveys/rapidsurveys.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-0T1H0GBVXG"
    anonymize-ip: true

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    toc: false